#!/usr/bin/env fish

# Usage:
#
# To enable fish <tab> completion for skypeit, add the following line to
# your ~/.config/fish/config.fish file:
#
# skypeit --completion=fish | source

complete -c skypeit -a "(skypeit --completion)" -f
